# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-storybook:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: npm run build-storybook
      - persist_to_workspace:
          paths:
            - storybook

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
  deploy-storybook:
    docker:
      - image: cibuilds/aws:1.16.185
    steps:
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync storybook/* s3://storybook-uds/ --delete
workflows:
  version: 2
  build-deploy-storybook:
    jobs:
      - build-storybook
      - deploy-storybook
          filters:
            branches:
              only: 
                 - /feature.*/
          